# Generated by Django 5.1.7 on 2025-04-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='image',
            field=models.ImageField(upload_to='coffee_images/https://i.pinimg.com/474x/58/52/3e/58523e6a3f2b4394ba69844644b44dea.jpg'),
        ),
    ]
