# Generated by Django 5.1.7 on 2025-04-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_alter_coffee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='image',
            field=models.ImageField(blank=True, default='default_coffee.jpg', null=True, upload_to='coffee_images/'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
