# Generated by Django 5.1.7 on 2025-04-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_alter_coffee_image_alter_coffee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='coffee_images/'),
        ),
    ]
