# Generated by Django 5.1.7 on 2025-04-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(default='No address provided', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='coffee',
            field=models.CharField(max_length=255),
        ),
    ]
