# Generated by Django 5.1.7 on 2025-04-28 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_alter_coffee_image'),
        ('orders', '0003_coffee_alter_order_coffee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coffee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.coffee'),
        ),
        migrations.DeleteModel(
            name='Coffee',
        ),
    ]
