# Generated by Django 5.1.7 on 2025-04-29 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_alter_coffee_image'),
        ('orders', '0006_coffee_alter_order_delivery_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coffee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.coffee'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Coffee',
        ),
    ]
